add_newline = false

format = "$all"

[aws]
disabled = true
[gcloud]
disabled = true

[character]
vicmd_symbol = "[V](bold green) "

[directory]
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false
format = " [📂 $path]($style)[$read_only]($read_only_style) "

[nodejs]
format = "via [ $version](bold green) "

[username]
style_user = "white bold"
style_root = "black bold"
format = " [$user]($style) "
disabled = false
show_always = true

# [battery]
# disabled = false
# show_always = true
#



